name: Mirror to GitLab

on:
  push:
    branches: ["main"]  # Activa el workflow al hacer push en main

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      # Clona el repositorio de GitHub con todo el historial
      - name: Checkout GitHub Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Clona todas las ramas y tags

      # Configura el usuario de Git
      - name: Configure Git
        run: |
          git config user.email "garcia.juanv97@gmail.com"
          git config user.name "Juan Garcia"

      # Agrega el repositorio de GitLab como remoto
      - name: Add GitLab Remote
        run: |
          git remote add gitlab https://${{ secrets.GITLAB_USERNAME }}:${{ secrets.GITLAB_TOKEN }}@gitlab.com/daftsu1/hello-world.git

      # Envía todo al repositorio de GitLab (ramas, tags, etc.)
      - name: Push to GitLab
        run: |
          git push --mirror gitlab
