name: Mirror Repository

on:
  schedule:
    - cron: '0 */6 * * *'  # Ejecutar cada 6 horas
  push:
    branches: [ main, master ]  # Ejecutar cuando se hace push a main o master
  workflow_dispatch:  # Permitir ejecución manual

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Push to mirror repository
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            https://${{ secrets.MIRROR_PAT }}@github.com/daftsu1/test-mirroring2.git
          #ssh_private_key:
            #${{ secrets.MIRROR_SSH_KEY }}  # Solo si usas SSH en lugar de PAT
