name: Mirror Repository

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Push to mirror repository
        run: |
          git remote add mirror https://${{ github.actor }}:${{ secrets.MIRROR_PAT }}@github.com/daftsu1/test-mirroring2.git
          git push --mirror mirror
